# Generated by Django 4.2.2 on 2023-06-30 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedTrainingPartner',
            fields=[
                ('partner_id', models.AutoField(primary_key=True, serialize=False)),
                ('partner_name', models.CharField(max_length=100)),
                ('partner_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('award_id', models.AutoField(primary_key=True, serialize=False)),
                ('award_title', models.CharField(max_length=100)),
                ('award_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('banner_id', models.AutoField(primary_key=True, serialize=False)),
                ('banner_image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CaseStudies',
            fields=[
                ('case_study_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_study_title', models.CharField(max_length=100)),
                ('case_study_description', models.TextField()),
                ('case_study_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.brand')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryFormat',
            fields=[
                ('delivery_format_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_format_name', models.CharField(max_length=100)),
                ('delivery_format_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain_id', models.AutoField(primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('footer_id', models.AutoField(primary_key=True, serialize=False)),
                ('social_media_icons', models.CharField(max_length=100)),
                ('join_us_link', models.URLField()),
                ('locations_link', models.URLField()),
                ('contact_us_link', models.URLField()),
                ('disclaimer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ForeignLanguageServices',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('header_id', models.AutoField(primary_key=True, serialize=False)),
                ('header_logo', models.ImageField(upload_to='header_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Industries',
            fields=[
                ('industry_id', models.AutoField(primary_key=True, serialize=False)),
                ('industry_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MainContent',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('banner_search_keyword', models.CharField(max_length=100)),
                ('authorized_training_partners', models.TextField()),
                ('why_choose_vinsys', models.TextField()),
                ('vinsys_portfolio', models.TextField()),
                ('news_title', models.CharField(max_length=100)),
                ('news_content', models.TextField()),
                ('news_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OurCoreValues',
            fields=[
                ('core_values_id', models.AutoField(primary_key=True, serialize=False)),
                ('core_values_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PressReleases',
            fields=[
                ('press_release_id', models.AutoField(primary_key=True, serialize=False)),
                ('press_release_title', models.CharField(max_length=100)),
                ('press_release_date', models.DateField()),
                ('press_release_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('subsubcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('subsubcategory_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VinsysPortfolio',
            fields=[
                ('portfolio_id', models.AutoField(primary_key=True, serialize=False)),
                ('portfolio_item', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Webinars',
            fields=[
                ('webinar_id', models.AutoField(primary_key=True, serialize=False)),
                ('webinar_title', models.CharField(max_length=100)),
                ('webinar_description', models.TextField()),
                ('webinar_date', models.DateField()),
                ('webinar_registration_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WhatIsNew',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_title', models.CharField(max_length=100)),
                ('news_content', models.TextField()),
                ('news_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Whitepapers',
            fields=[
                ('whitepaper_id', models.AutoField(primary_key=True, serialize=False)),
                ('whitepaper_title', models.CharField(max_length=100)),
                ('whitepaper_description', models.TextField()),
                ('whitepaper_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseVinsys',
            fields=[
                ('choose_id', models.AutoField(primary_key=True, serialize=False)),
                ('choose_title', models.CharField(max_length=100)),
                ('choose_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WebinarRegistrations',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('registration_date', models.DateField()),
                ('webinar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.webinars')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('training_id', models.AutoField(primary_key=True, serialize=False)),
                ('training_name', models.CharField(max_length=100)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.course')),
                ('delivery_format_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.deliveryformat')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.subcategory')),
                ('subsubcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.subsubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.services')),
                ('subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('quote_id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.TextField()),
                ('pricing', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.products')),
                ('subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction_content', models.TextField()),
                ('instructor_section', models.TextField()),
                ('skill_gaps_section', models.TextField()),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.training')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPrivateTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction_content', models.TextField()),
                ('group_private_training_benefits_section', models.TextField()),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.training')),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction_content', models.TextField()),
                ('government_solutions_section', models.TextField()),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.training')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.user')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiries',
            fields=[
                ('enquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.user')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='domain_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.domain'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.user'),
        ),
        migrations.CreateModel(
            name='CorporateTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction_content', models.TextField()),
                ('learning_pass_section', models.TextField()),
                ('soft_skills_section', models.TextField()),
                ('domain_brand_training_section', models.TextField()),
                ('authorizations_section', models.TextField()),
                ('locations_section', models.TextField()),
                ('corporate_training_benefits_section', models.TextField()),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.training')),
            ],
        ),
    ]
